version: '3'

services:

  redis:
    image: redis
    
  mongo:
    image: mongo    
    ports:
      - "27017:27017"  

  cc-api:
    build: 
      context: "./ccApi"
      dockerfile: Dockerfile
    image: cc-api
    ports: 
      - "8080:8080"
    links: 
      - mongo
    depends_on:
      - mongo
    environment: 
      - DOCKER="true"
    command: ["npm", "start"]
    external_links: 
      - cc-client

  cc-server:
  
    build: 
      context: "./ccServer"
      dockerfile: Dockerfile
    image: cc-server
    ports: 
      - "3000:3000"
    links:
      - redis
    depends_on:
      - redis
      - cc-api
    environment: 
      - DOCKER="true"
    command: ["npm", "start"]

  cc-client:
  
    build: 
      context: "./ccClient"
      dockerfile: Dockerfile
    image: cc-client
    ports:
      - "4200:80"
    depends_on:
      - cc-server
      - cc-api
    links:
      - cc-api
    external_links: 
      - cc-api